name: CI/CD pour Angular sur Docker
#nom du workflow
#définit les événements qui déclenchent les événements:quand on push sur la main.
#hoplaboumpour pouvoir pusher
on:
  push:
    branches:
      - main

jobs:
  BuildetTeste:
    runs-on: ubuntu-latest
    steps:
      - name: GetRepository
        uses: actions/checkout@v5
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: Install dependencies
        run: npm ci

      - name: Build app Angular
        run: npm run build --if-present

      - name: Tests
        run: npm test -- --watch=false --browsers=ChromeHeadless --code-coverage
        continue-on-error: false

      - name: Log in to Docker Hub 
        uses: docker/login-action@v3
        with: 
          username: ${{ secrets.SECRET_NAME }}
          password: ${{ secrets.SECRET_CODE}}
      
      - name: Build et push image Docker
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.SECRET_NAME }}/angularapp:latest